services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234!
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  setup:
    build: ../setup
    command: ./entrypoint.sh
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: abcd1234!
      DB_NAME_HOCUSPOCUS: hocuspocus
      DB_USER_HOCUSPOCUS: hocuspocus_user
      DB_PASSWORD_HOCUSPOCUS: abcd1234!
      DB_NAME_SERVER: server
      DB_USER_SERVER: server_user
      DB_PASSWORD_SERVER: abcd1234!
      DB_PASSWORD_SUPERUSER: abcd1234!
      APP_NAME: sebastian
      APP_ENV: development
      DB_TYPE: postgres
    depends_on:
      postgres:
        condition: service_healthy
