{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  DB_PASSWORD_HOCUSPOCUS: {{ randAlphaNum 32 | b64enc | quote }}
  DB_PASSWORD_SERVER: {{ randAlphaNum 32 | b64enc | quote }}
  DB_PASSWORD_SUPERUSER: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}