{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.db.service.port }}
  selector:
    app: db
{{- end }}