apiVersion: v1
kind: Secret
metadata:
    name: "{{include "sebastian.fullname" .}}-secrets"
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    NEXTAUTH_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
    CRYPTR_KEY: {{ randAlphaNum 32 | b64enc | quote }}
    TOKEN_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}