apiVersion: v1
kind: Service
metadata:
  name: {{ include "sebastian.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sebastian.selectorLabels" . | nindent 4 }}
