apiVersion: v1
kind: Service
metadata:
  name: hocuspocus
  namespace: {{ .Values.namespace }}
  labels:
    app: hocuspocus
spec:
  type: {{ .Values.hocuspocus.service.type }}
  ports:
    - port: {{ .Values.hocuspocus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hocuspocus
